### ISSUE TITLE
auto clear databrowser/sweepbrowser of overlayed sweeps

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#303] opened 2019-09-28 21:08 UTC
It's common for users to overlay all the sweeps from a stimulus set or an RA cycle during data acquisition. At the start of a new RA cycle, users have to select the `none` stimulus set to clear the overlayed sweeps. It would be helpful to have an option to autoclear previously overlayed sweeps when a new stimulus or RA cycle begins. I'm imagining two checkboxes in the OS panel of the sweep/data browser.

(1) Clear sweeps on new RA cycle
(2) Clear sweeps on new stimset (used when indexing through several stimulus sets)

**Comment by t-b** [comment] 2019-09-29 13:53
I'll tackle this here.

Can it be that https://github.com/AllenInstitute/MIES/issues/264 is a duplicate of this bug here?

**Closed** 2019-10-09 10:56 UTC
Labels: DataAcquisition, DataBrowser/SweepBrowser, Overlay sweeps
