### ISSUE TITLE
Optionally clear data browser sweeps with new RA cycle and/or new stim set

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#264] opened 2019-09-07 11:42 UTC
In cases where the user is acquiring a single stimset at a time and using display last sweep acquired in combination with overlay sweeps, they often clear the data browser plot on each RA cycle manually by selecting the 'none'  stimulus set in overlay sweeps tab. Let's give the user the option to do this automatically on each new RA cycle.

**Comment by t-b** [comment] 2019-10-07 07:39
Duplicate of #303.

**Closed by t-b** 2019-10-07 07:39 UTC
Labels: DataBrowser, DataBrowser/SweepBrowser, Overlay sweeps
