### ISSUE TITLE
Add more amplifier settings to TPStorage

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1308] opened 2022-03-09 20:19 UTC
We already store amplifier settings in the labnotebook after a TP run, see ED_TPDocumentation.
It would be nice to store these amplifier settings also for each TP in TPStorage.

One problem is that we query *and* select the amplifier in ED_TPDocumentation and that is terribly slow. We do that because we don't trust the MIES GUI for amplifier settings as the user might have changed some settings in the MCC app.

One solution could be to monitor the MCC settings continously from a thread and use those settings when writing into the TPStorage wave. That also requires us to make the MCC XOP functions threadsafe.

**Comment by timjarsky** [comment] 2022-09-27 22:08
@t-b closing, a duplicate of #1317

**Closed by timjarsky** 2022-09-27 22:08 UTC
Labels: enhancement, Amplifier
