### ISSUE TITLE
After changing DA/ADC channel in DA_Ephys HW tab, can not start TP/DAQ with error 'The unit for ADCchannel x is empty."

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#103] opened 2018-12-07 11:28 UTC
Also happens with error "The unit for DACchannel x is empty."

Current work around is to click "Auto Fill".

**Comment by t-b** [comment] 2018-12-08 12:19
That is actually not a bug but how you have to configure MIES at the moment. Setup the headstage<->Amplifier connection in the hardware tab, use `Auto Fill` to get the settings and then start DAQ.

**Comment by t-b** [comment] 2018-12-14 12:59
This should work automatically if we can do it.

**Comment by t-b** [comment] 2019-01-15 22:32
Fixed in PR 1064.

**Closed by t-b** 2019-01-15 22:32 UTC
Labels: DataAcquisition, bug
