### ISSUE TITLE
SweepFormula: Support of sweeps with non-matching sampling interval and multiple ranges

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#362] opened 2019-11-08 13:09 UTC
> 
> Possible solutions:
> 
> * Let `data` return a wave reference wave with the correct x scaling for each extracted sweep
> * Use the union of all sweep ranges and fit the data into it
> 
@t-b @ukos-git  If we have the resources, I propose we only resample when necessary. For example, averaging two waves together will require resampling, but taking the mean of two waves does not. In this way, we can mostly avoid issues that come with resampling (changing the data, ringing, etc.) but the user experience is seamless.

_Originally posted by @timjarsky in https://github.com/AllenInstitute/MIES/pull/339#issuecomment-551224867_

**Comment by t-b** [comment] 2019-11-08 13:10
@timjarsky I'm not understanding why average and mean would behave differently for sweeps with a different sampling interval.

**Comment by timjarsky** [comment] 2019-11-08 14:33
@t-b 
Average, like the pink average wave in the data browser.

Mean, a single value calculated for the wave, like we currently do in sweep formula.

Sorry for the previous muddy comment. I hope this one clears things up?

**Comment by t-b** [comment] 2019-11-08 14:35
@timjarsky Got it, thanks for the clarification.

**Comment by t-b** [comment] 2021-09-09 09:37
Another variant of this bug is that `data` does not accept multiple ranges.

**Comment by t-b** [comment] 2021-11-19 17:40
@MichaelHuth Next time we chat: Let's discuss this item.

The first task is to estimate the amount of work it takes to solve that.

**Comment by ukos-git** [comment] 2021-11-19 18:20
I am free next week to give you a head‘s up introduction on the code structure.

**Comment by MichaelHuth** [comment] 2022-01-28 16:59
## Changing the SweepFormula way to store data

Currently we have the problem that we return on each step only a wave that contains the data itself.
This results in follow up issues, where if e.g. sweep data is returned in a 3D wave, requiring that all sweeps have the same delta and length. Also there is no general way to attach meta information, like source sweep number/channel to the data easily.

## Approach

We introduce a new wave format for returning data. Instead of data point the wave contains wave references.
The wave type should be sufficient to identify the new wave.

This wave references free waves, e.g. one wave with sweep data per element.
At the end the FormulaPlotter has to convert waves to plot in persistent waves in a working data folder that contains the waves for the traces displayed. Each referenced wave in there must be a regular numerical/textual wave.
This is better for memory management. 

We can store meta data in the Dimlabels and WaveNote. Do we need to store data in the note of the wave ref wve too? 

The WaveNote has JSON Format?

If Operation use source data from MIES, like data(), the data must be copied to a free wave in the operation.
Such that the data treatment starts with free waves and ends with a free wave. The referenced waves in the returned wave reference wave must be numerical/textual. 

As each operation stands for its own, for simple operations like addition, we do not have to duplicate for an output wave but we can apply the data treatment in-place.

## Dependent Issues

- specify for each operation the possible input and output data formats
- users need still the classic input format, as they can not input wave ref waves

## Codeflow properties

- only the data input entry points where user data is input use the classic numerical/textual waves -> all returned waves are free wave ref waves (e.g. think of separate ranges for each sweep).
- For debugging we duplicate the referenced waves returned to a debugging DF with unique names, like `R<X>_<OperationName>_UniqueSuffix`, where X is the recursion level.

## Example for data

range input is classic or wave ref wave with one or N elements. If N elements, N must equal the number of sweeps. Each referenced wave is two elements numerical.

sweep input is classic or wave ref wave with one element, a numerical wave with N elements.

channels is effectively the same concept as range

Each sweep gets the retrieved as a free wave duplicate of the 1D sweep data with sweep number and channel number/type information stored in its wave note. All duplicated sweeps are collected in a wave reference wave. This wave reference wave is returned by the operation.

Previous restrictions for delta or range specific copying into an 3D wave are not necessary any more.

The FormulaPLotter gets this wave ref wave and **moves** each referenced sweep to a persistent wave in a working data folder. It iterates over the wave refs for plotting, that point now to persistent waves. This replaces the iteration over columns * layers as done now.

**Comment by t-b** [comment] 2022-05-04 14:58
Milestone 1:
- Extend tests to ensure existing functionality keeps working

Milestone 2:
- Move `+` operation to new format
- Adapt plotter to new format

Milesone 3:
- Add debug mode where every free wave used for data storage is permanent in the working folder
- Skip input data cleanup in debug mode

Milestone 4:
- Move `channels/sweeps/select/data` operations to new format
- Get preserve channel information working in the plotter
- Get non-matching sampling interval working for `data`

Milestone 5 and more:
TBD

**Closed** 2022-08-25 11:57 UTC
Labels: bug, SweepFormula
